# R2dbc-Dsl

This module provides `R2dbcDslRepository` for Web Querying throw REST API and Criteria building via `R2dbcDsl` class.

Also provides Spring Static Application Context with access to Spring beans and environments
and Fast Method implementation for quickly setter/getter of object properties. Also including
Kotlin Extensions for more cleaning source code.

Add the Maven dependency:

[source,xml]
----
<dependency>
  <groupId>io.github.sevenparadigms</groupId>
  <artifactId>r2dbc-dsl</artifactId>
  <version>1.2.4</version>
</dependency>
----

That repository produce `R2dbcDslRepository` interface:
[source,kotlin]
----
interface R2dbcDslRepository<T, ID> : ReactiveCrudRepository<T, ID> {
    fun <S : Any> saveBatch(entities: Iterable<S>): Flux<Int>
    fun listen(): Sink<Notification>
    fun findAll(dsl: R2dbcDsl, pageable: Pageable): Flux<T>
    fun findAll(pageable: Pageable): Flux<T>
    fun findBy(dsl: R2dbcDsl): Mono<T>
    fun fts(dsl: R2dbcDsl, pageable: Pageable): Flux<T>
    fun oper(dsl: R2dbcDsl, pageable: Pageable): Flux<T>
}
----

## Features

1. Paging and Sorting full support with ordering in several columns at once

2. Dsl support all SQL predicates: `=, >, <, >=, <=, like, in, not in, is true, is false, is null, is not null`

3. Ability to select columns in `findAll(dsl: R2dbcDsl, pageable: Pageable)` and `findBy(dsl: R2dbcDsl)` methods

4. Joins to any tables and build criteria on joined columns, also select joined columns in result

5. Annotation `@Id` is not required in model, because column ID in 90% tables it is a column ID

6. Annotation `@Table` is not required in model, because table name get from model class name

7. Collection saving in Batch mode

#### for PostgreSQL:

8. In query can refer on value of Jsonb type as path: jdata.profile.area==Rocks Valley;jdata.type==Sentinel

9. Method `repository.listen(): Sink<Notification>` subscribe to INSERT/UPDATE events on table from database

10. Method `repository.fts(dsl: R2dbc, pageable: Pageable)` return ranked full-text search result

11. Method `repository.oper(dsl: R2dbc, pageable: Pageable)` used for call inline operators: `@>, @?, @@ ...`

Often in dynamically created classes needed access to `application.properties` or Spring beans
with protection against a premature call during Application and beans depends start-up in runtime.
Also Application Context can dynamically register beans from static context.

Utility class `FastMethodInvoker` is a modern reflection access to object properties.

## Concepts

The main idea is to reduce development time when all kinds of criteria can be formed at the frontend:

`localhost:8080/items?query=shops.type==mega;name~~biggest;price>=100 & fields=id;name & page=0 & size=20 & sort=itemType:asc,createdAt:desc`

then generated SQL:

`select id, name from items join shops on items.shop_id = shops.id where shops.type='mega' and name like '%biggest%' and price >= 100 order by item_type asc, created_at desc limit 20 offset 0`

## Get started

Create empty configuration class with annotations:

[source,kotlin]
----
import com.sevenparadigms.dsl.R2dbcDslConfiguration
import com.sevenparadigms.dsl.R2dbcDslRepositoryFactoryBean

@EnableR2dbcRepositories(basePackages = ["com.example"], repositoryFactoryBeanClass = R2dbcDslRepositoryFactoryBean::class)
@ImportAutoConfiguration(R2dbcDslConfiguration::class)
class CustomR2dbcDslConfiguration {}
----

and import it in Application class:
[source,kotlin]
----
@EnableR2dbcRepositories
@ImportAutoConfiguration(CustomR2dbcDslConfiguration::class)
----
then all Dsl Repositories in package "com.example" will earn.
[source,kotlin]
----
repository.findAll(dsl, serverRequest.getPageable())
----

The same happens using the database client:
[source,kotlin]
----
val dsl = R2dbcDsl.create().id(100L).getCriteriaBy(Entity::class)
client.select().from(Entity::class).matching(dsl).fetch().one()
----

#### Web query predicates (-> sql):

* "column##1 2 3" -> column in (1, 2, 3)
* "column!#1 2 3" -> column not in (1, 2, 3)
* "column==value" -> column = value
* "column!=value" -> column != value
* "column" -> column is true
* "!column" -> column is not true
* "@column" -> column is null
* "!@column" -> column is not null
* "column>>value" -> column > value
* "column>=value" -> column >= value
* "column<<value" -> column < value
* "column<=value" -> column <= value
* "column~~value" -> column like '%value%'

#### Web query columns:

* column -> used as is
* column.type -> join table if column is not JsonNode type (model must contain columnId variable)
* column.header.title -> `column->'header'->>'title'` if column have JsonNode type

In `fields` property can selected joined columns or jsonb path to output result.
For example `columnType` or `columnHeaderTitle` and model must contain these variables.

#### Subscribe to async database UPDATE/INSERT events:

Before create universal notifier function:
[source,postgresql]
----
create function notify_sender() returns trigger
    language plpgsql
as
$$
BEGIN
    PERFORM pg_notify(
                    TG_TABLE_NAME,
                    json_build_object(
                            'operation', TG_OP,
                            'record', row_to_json(NEW)
                        )::text
                );
    RETURN NULL;
END;
$$;
----
And set to tables notifier by trigger:
[source,postgresql]
----
create trigger table_notify
    after insert or update
    on table
    for each row
execute procedure notify_sender();
----
In the next version of R2dbcDslRepository, it will create a trigger on first access is required.

== Example

* https://github.com/SevenParadigms/r2dbc-dsl-ecommerce/[R2dbc Dsl Example as E-Commerce starting project] contains project that explain specific features.

== Road map

* https://github.com/SevenParadigms/r2dbc-dsl/wiki[Painted on Wiki]
