# R2dbc-Dsl

This module provides `R2dbcDslRepository` for Web Querying throw REST API and Criteria building via `R2dbcDsl` class.
Working with PostgreSQL, MySQL, Oracle, MSSql

Add the Maven dependency:

[source,xml]
----
<dependency>
  <groupId>io.github.sevenparadigms</groupId>
  <artifactId>spring-data-r2dbc-dsl</artifactId>
  <version>2.6.0</version>
</dependency>
----

That repository produce `R2dbcDslRepository` interface:
[source,kotlin]
----
interface R2dbcDslRepository<T, ID> : ReactiveCrudRepository<T, ID> {
    fun findOne(dsl: Dsl): Mono<T>
    fun findAll(dsl: Dsl): Flux<T>
}
----

## Features

1. Paging and Sorting full support with ordering in several columns at once

2. Dsl support all SQL predicates: `=, >, <, >=, <=, like, in, not in, is true, is false, is null, is not null`

3. Ability to select columns in `findAll(dsl: R2dbcDsl, pageable: Pageable)` and `findBy(dsl: R2dbcDsl)` methods

4. Joins to any tables and build criteria on joined columns, also select joined columns in result

5. Annotation `@Id` is not required in model, because column ID in 90% tables it is a column ID

6. Annotation `@Table` is not required in model, because table name get from model class name

7. Collection saving in Batch mode

#### for PostgreSQL:

8. In query can refer on value of Jsonb type as path: jdata.profile.area==Rocks Valley;jdata.type==Sentinel

9. Method `repository.listen(): Sink<Notification>` subscribe to INSERT/UPDATE events on table from database

Often in dynamically created classes needed access to `application.properties` or Spring beans
with protection against a premature call during Application and beans depends start-up in runtime.
Also Application Context can dynamically register beans from static context.

Utility class `FastMethodInvoker` is a modern reflection access to object properties.

## Concepts

The main idea is to reduce development time when all kinds of criteria can be formed at the frontend:

`localhost:8080/items?query=shops.type==mega;name~~biggest;price>=100 & fields=id;name & page=0 & size=20 & sort=itemType:asc,createdAt:desc`

then generated SQL:

`select id, name from items join shops on items.shop_id = shops.id where shops.type='mega' and name like '%biggest%' and price >= 100 order by item_type asc, created_at desc limit 20 offset 0`

#### Web query predicates (-> sql):

* "column##1 2 3" -> column in (1, 2, 3)
* "column!#1 2 3" -> column not in (1, 2, 3)
* "column==value" -> column = value
* "column!=value" -> column != value
* "column" -> column is true
* "!column" -> column is not true
* "@column" -> column is null
* "!@column" -> column is not null
* "column>>value" -> column > value
* "column>=value" -> column >= value
* "column<<value" -> column < value
* "column<=value" -> column <= value
* "column~~value" -> column like '%value%'

#### Web query columns:

* column -> used as is
* column.type -> join table if column is not JsonNode type (model must contain columnId variable)
* column.header.title -> `column->'header'->>'title'` if column have JsonNode type

In `fields` property also can selected joined columns or jsonb path to output result.
For example `columnType` or `columnHeaderTitle` from previous example and model must contain these variables.
