/*
 * Copyright 2018-2021 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.data.r2dbc.repository;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.hazelcast.core.Hazelcast;
import io.r2dbc.spi.ConnectionFactory;
import io.r2dbc.spi.Result;
import lombok.AllArgsConstructor;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.api.extension.RegisterExtension;
import org.sevenparadigms.cache.hazelcast.HazelcastCacheConfiguration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.ComponentScan.Filter;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.FilterType;
import org.springframework.data.r2dbc.config.AbstractR2dbcConfiguration;
import org.springframework.data.r2dbc.config.Beans;
import org.springframework.data.r2dbc.expression.ExpressionParserCache;
import org.springframework.data.r2dbc.mapping.event.BeforeConvertCallback;
import org.springframework.data.r2dbc.repository.cache.AbstractRepositoryCache;
import org.springframework.data.r2dbc.repository.config.EnableR2dbcRepositories;
import org.springframework.data.r2dbc.repository.query.Dsl;
import org.springframework.data.r2dbc.support.DslUtils;
import org.springframework.data.r2dbc.support.JsonUtils;
import org.springframework.data.r2dbc.testing.ExternalDatabase;
import org.springframework.data.r2dbc.testing.PostgresTestSupport;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.r2dbc.core.DatabaseClient;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.util.Assert;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.test.StepVerifier;

import javax.sql.DataSource;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.time.ZonedDateTime;
import java.time.temporal.ChronoUnit;
import java.util.*;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for {@link LegoSetRepository} using {linkRepositoryFactorySupport} against Postgres.
 *
 * @author Mark Paluch
 * @author Jose Luis Leon
 */
@ExtendWith(SpringExtension.class)
@ContextConfiguration(classes = { HazelcastCacheConfiguration.class, PostgresR2dbcRepositoryIntegrationTests.IntegrationTestConfiguration.class })
@TestPropertySource(properties = {
		"spring.r2dbc.dsl.cacheManager=true",
		"spring.r2dbc.dsl.equality=nameEquality",
		"spring.r2dbc.dsl.readOnly=manualReadOnly",
		"spring.r2dbc.dsl.version=counterVersion",})
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class PostgresR2dbcRepositoryIntegrationTests extends AbstractR2dbcRepositoryIntegrationTests {

	@RegisterExtension public static final ExternalDatabase database = PostgresTestSupport.database();

	@Autowired WithJsonRepository withJsonRepository;

	@Autowired WithHStoreRepository hstoreRepositoryWith;

	@Configuration
	@EnableR2dbcRepositories(considerNestedRepositories = true,
			includeFilters = @Filter(
					classes = { PostgresLegoSetRepository.class, WithJsonRepository.class, WithHStoreRepository.class },
					type = FilterType.ASSIGNABLE_TYPE))
	static class IntegrationTestConfiguration extends AbstractR2dbcConfiguration {

		@Bean
		@Override
		public ConnectionFactory connectionFactory() {
			return PostgresTestSupport.createConnectionFactory(database);
		}

		@Bean
		public BeforeConvertCallback<LegoSet> autogeneratedId(DatabaseClient client) {

			return (entity, table) -> {

				if (entity.getId() == null) {
					return client.sql("SELECT nextval('person_seq');") //
							.map(row -> row.get(0, Integer.class)) //
							.first() //
							.doOnNext(entity::setId) //
							.thenReturn(entity);
				}

				return Mono.just(entity);
			};
		}
	}

	@Override
	protected DataSource createDataSource() {
		return PostgresTestSupport.createDataSource(database);
	}

	@Override
	protected ConnectionFactory createConnectionFactory() {
		return PostgresTestSupport.createConnectionFactory(database);
	}

	@Override
	protected String getCreateTableStatement() {
		return PostgresTestSupport.CREATE_TABLE_LEGOSET + ";CREATE SEQUENCE IF NOT EXISTS person_seq;";
	}

	@Override
	protected Class<? extends LegoSetRepository> getRepositoryInterfaceType() {
		return PostgresLegoSetRepository.class;
	}

	interface PostgresLegoSetRepository extends LegoSetRepository {

		@Override
		@Query("SELECT name from lego_set")
		Flux<Named> findAsProjection();

		@Override
		@Query("SELECT * from lego_set WHERE manual = :manual")
		Mono<LegoSet> findByManual(int manual);

		@Override
		@Query("SELECT id from lego_set")
		Flux<Integer> findAllIds();
	}

	@Test
	void shouldSaveAndLoadJson() {

		JdbcTemplate template = new JdbcTemplate(createDataSource());

		template.execute("DROP TABLE IF EXISTS with_json");
		template.execute("CREATE TABLE with_json (\n" //
				+ "    id          SERIAL PRIMARY KEY,\n" //
				+ "    json_value  JSONB NOT NULL" //
				+ ");");

		WithJson person = new WithJson(null, JsonUtils.getMapper().createObjectNode().put("hello", "world"));
		withJsonRepository.save(person).as(StepVerifier::create).expectNextCount(1).verifyComplete();

		withJsonRepository.findAll().as(StepVerifier::create).consumeNextWith(actual -> {

			assertThat(actual.jsonValue).isNotNull();
			assertThat(actual.jsonValue.toString()).isEqualTo("{\"hello\":\"world\"}");
		}).verifyComplete();
	}

	@Test // gh-492
	void shouldSaveAndLoadHStore() {

		JdbcTemplate template = new JdbcTemplate(createDataSource());

		template.execute("DROP TABLE IF EXISTS with_hstore");
		template.execute("CREATE EXTENSION IF NOT EXISTS hstore;");
		template.execute("CREATE TABLE with_hstore (" //
				+ "    id            SERIAL PRIMARY KEY," //
				+ "    hstore_value  HSTORE NOT NULL);");

		WithHstore person = new WithHstore(null, Collections.singletonMap("hello", "world"));
		hstoreRepositoryWith.save(person).as(StepVerifier::create).expectNextCount(1).verifyComplete();

		hstoreRepositoryWith.findAll().as(StepVerifier::create).consumeNextWith(actual -> assertThat(actual.hstoreValue).isNotNull().containsEntry("hello", "world")).verifyComplete();
	}

	@AllArgsConstructor
	static class WithJson implements Serializable {

		/*@Id */Long id;

		JsonNode jsonValue;

		public Long getId() {
			return id;
		}

		public JsonNode getJsonValue() {
			return jsonValue;
		}
	}

	interface WithJsonRepository extends R2dbcRepository<WithJson, Long> {

	}

	@AllArgsConstructor
//	@Table("with_hstore")
	static class WithHstore implements Serializable {

		/*@Id */Long id;

		Map<String, String> hstoreValue;

		public Long getId() {
			return id;
		}

		public Map<String, String> getHstoreValue() {
			return hstoreValue;
		}
	}

	interface WithHStoreRepository extends R2dbcRepository<WithHstore, Long> {

	}

	@Test
	void shouldAnnotationsVerify() {
		List<LegoSet> legoSets = shouldInsertNewItems();

		repository.findById(2)
				.as(StepVerifier::create)
				.consumeNextWith(actual -> {
					assertThat(actual.getName()).isEqualTo("FORSCHUNGSSCHIFF");
					assertThat(actual.getManual()).isEqualTo(13);
					assertThat(actual.getVersion()).isEqualTo(1);
					assertThat(actual.getNow()).isNotNull();
				})
				.verifyComplete();

		// try to change equality attr name and get exception
		var legoSet = legoSets.get(1);
		legoSet.setName("123");

		repository.save(legoSet) //
				.as(StepVerifier::create) //
				.expectError(IllegalStateException.class);

		// try to change readonly attr manual and get old value
		legoSet.setName("FORSCHUNGSSCHIFF");
		legoSet.setManualReadOnly(123);

		repository.save(legoSet) //
				.as(StepVerifier::create) //
				.consumeNextWith(actual -> assertThat(actual.getManualReadOnly()).isEqualTo(22))
				.verifyComplete();

		// try to change equality attr from properties name and get exception
		legoSet = legoSets.get(1);
		legoSet.setNameEquality("123");

		repository.save(legoSet) //
				.as(StepVerifier::create) //
				.expectError(IllegalStateException.class);

		// try to change readonly attr from properties manual and get old value
		legoSet.setNameEquality("equality");
		legoSet.setManualReadOnly(123);

		repository.save(legoSet) //
				.as(StepVerifier::create) //
				.consumeNextWith(actual -> assertThat(actual.getManual()).isEqualTo(13))
				.verifyComplete();

		// check versions
		repository.findById(2)
				.as(StepVerifier::create)
				.consumeNextWith(actual -> {
					assertThat(actual.getVersion()).isEqualTo(3);
					assertThat(actual.getCounterVersion()).isEqualTo(3);
				})
				.verifyComplete();
	}

	@Test
	void shouldSimpleDsl() {
		List<LegoSet> legoSets = shouldInsertNewItems();
		assert legoSets.size() == 2;

		repository.findOne(Dsl.create().equals("manual", 13))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> assertThat(actual.getName()).isEqualTo("FORSCHUNGSSCHIFF"))
				.verifyComplete();

		repository.findOne(Dsl.create().notEquals("manual", 13))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> assertThat(actual.getName()).isEqualTo("SCHAUFELRADBAGGER"))
				.verifyComplete();

		repository.findOne(Dsl.create().notEquals("name", "SCHAUFELRADBAGGER"))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> assertThat(actual.getName()).isEqualTo("FORSCHUNGSSCHIFF"))
				.verifyComplete();

		repository.findOne(Dsl.create().equals("name", "FORSCHUNGSSCHIFF"))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> assertThat(actual.getManual()).isEqualTo(13))
				.verifyComplete();

		repository.findOne(Dsl.create().like("name", "UNGSS"))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> assertThat(actual.getManual()).isEqualTo(13))
				.verifyComplete();

		repository.findOne(Dsl.create().id(1L))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> assertThat(actual.getName()).isEqualTo("SCHAUFELRADBAGGER"))
				.verifyComplete();

		repository.findOne(Dsl.create().in("id", 1L))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> assertThat(actual.getName()).isEqualTo("SCHAUFELRADBAGGER"))
				.verifyComplete();

		repository.findAll(Dsl.create())
				.as(StepVerifier::create)
				.expectNextCount(2) //
				.verifyComplete();

		repository.findOne(Dsl.create().sorting("id", "desc"))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.getId().longValue() == 2, "must 2"))
				.verifyComplete();

		repository.findOne(Dsl.create().sorting("id", "desc").pageable(1, 1))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.getId().longValue() == 1, "must 1"))
				.verifyComplete();

		repository.findAll(Dsl.create().greaterThanOrEquals("id", 1L).limit(2))
				.as(StepVerifier::create)
				.expectNextCount(2) //
				.verifyComplete();

		repository.findAll(Dsl.create().greaterThanOrEquals("id", 2L).limit(1))
				.as(StepVerifier::create)
				.expectNextCount(1) //
				.verifyComplete();

		repository.findAll(Dsl.create().greaterThanOrEquals("id", 2L).fields(" id", "name").limit(1))
				.as(StepVerifier::create)
				.expectNextCount(1) //
				.verifyComplete();

		repository.findAll(Dsl.create().notIn("id", 2L).fields(" id", "name").limit(1))
				.as(StepVerifier::create)
				.expectNextCount(1) //
				.verifyComplete();

		repository.findAll(Dsl.create().in("id", 1L).in("name", "SCHAUFELRADBAGGER").fields(" id", "name").limit(1))
				.as(StepVerifier::create)
				.expectNextCount(1) //
				.verifyComplete();
	}

	@Test
	void shouldCompareDates() {
		var now = LocalDate.now();
		var nowTime = LocalDateTime.now();
		var zonedTime = ZonedDateTime.now();
		var offsetTime = OffsetDateTime.now();

		LegoSet legoSet1 = new LegoSet(null, "SCHAUFELRADBAGGER", 12);
		legoSet1.setData(now.minus(1, ChronoUnit.DAYS));
		legoSet1.setDataTime(nowTime.minus(1, ChronoUnit.DAYS));
		legoSet1.setZonedTime(zonedTime.minus(1, ChronoUnit.DAYS));
		legoSet1.setOffsetTime(offsetTime.minus(1, ChronoUnit.DAYS));

		LegoSet legoSet2 = new LegoSet(null, "FORSCHUNGSSCHIFF", 13);
		legoSet2.setData(now);
		legoSet2.setDataTime(nowTime);
		legoSet2.setZonedTime(zonedTime);
		legoSet2.setOffsetTime(offsetTime);

		LegoSet legoSet3 = new LegoSet(null, "FORSCHUNGSSCHIFF", 13);
		legoSet3.setData(now.plus(1, ChronoUnit.DAYS));
		legoSet3.setDataTime(nowTime.plus(1, ChronoUnit.DAYS));
		legoSet3.setZonedTime(zonedTime.plus(1, ChronoUnit.DAYS));
		legoSet3.setOffsetTime(offsetTime.plus(1, ChronoUnit.DAYS));

		repository.saveBatch(List.of(legoSet1, legoSet2, legoSet3)).flatMap(Result::getRowsUpdated)
				.as(StepVerifier::create)
				.expectNextCount(3) //
				.verifyComplete();

		repository.findAll(Dsl.create().greaterThan("data", now)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 3, "must equals"))
				.verifyComplete();
		repository.findAll(Dsl.create().lessThan("data", now)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 1, "must equals"))
				.verifyComplete();
		repository.findAll(Dsl.create().lessThanOrEquals("data", now))
				.as(StepVerifier::create)
				.expectNextCount(2) //
				.verifyComplete();
		repository.findAll(Dsl.create().equals("data", now)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 2, "must equals"))
				.verifyComplete();

		repository.findAll(Dsl.create().greaterThan("dataTime", nowTime)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 3, "must equals"))
				.verifyComplete();
		repository.findAll(Dsl.create().lessThan("dataTime", nowTime)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 1, "must equals"))
				.verifyComplete();
		repository.findAll(Dsl.create().greaterThanOrEquals("dataTime", nowTime))
				.as(StepVerifier::create)
				.expectNextCount(2) //
				.verifyComplete();
		repository.findAll(Dsl.create().equals("dataTime", nowTime)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 2, "must equals"))
				.verifyComplete();

		repository.findAll(Dsl.create().greaterThan("zonedTime", zonedTime)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 3, "must equals"))
				.verifyComplete();
		repository.findAll(Dsl.create().lessThan("zonedTime", zonedTime)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 1, "must equals"))
				.verifyComplete();
		repository.findAll(Dsl.create().greaterThanOrEquals("zonedTime", zonedTime))
				.as(StepVerifier::create)
				.expectNextCount(2) //
				.verifyComplete();
		repository.findAll(Dsl.create().equals("zonedTime", zonedTime)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 2, "must equals"))
				.verifyComplete();

		repository.findAll(Dsl.create().greaterThan("offsetTime", offsetTime)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 3, "must equals"))
				.verifyComplete();
		repository.findAll(Dsl.create().lessThan("offsetTime", offsetTime)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 1, "must equals"))
				.verifyComplete();
		repository.findAll(Dsl.create().greaterThanOrEquals("offsetTime", offsetTime))
				.as(StepVerifier::create)
				.expectNextCount(2) //
				.verifyComplete();
		repository.findAll(Dsl.create().equals("offsetTime", offsetTime)).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.get(0).id == 2, "must equals"))
				.verifyComplete();
	}

	@Test
	void shouldBatch() {
		LegoSet legoSet1 = new LegoSet(null, "SCHAUFELRADBAGGER", 12);
		LegoSet legoSet2 = new LegoSet(null, "FORSCHUNGSSCHIFF", 13);

		repository.saveBatch(List.of(legoSet1, legoSet2))
				.as(StepVerifier::create)
				.expectNextCount(2) //
				.verifyComplete();
	}

	@Test
	void shouldBeans() throws JsonProcessingException {
		Assert.notNull(Beans.getApplicationContext(), "Application context must not be null!");
		Assert.notNull(Beans.of(DatabaseClient.class), "DatabaseClient must not be null!");
		Assert.isTrue(Beans.of(ObjectMapper.class).readTree("{'name':'value'}").toString().equals("{\"name\":\"value\"}"), "is not true");
		Assert.notNull(Beans.of(ExpressionParserCache.class), "ExpressionParserCache must not be null!");
	}

	static class CacheTest extends AbstractRepositoryCache<String, UUID> {
		public CacheTest() {
			super(null, Beans.getApplicationContext());
			Assert.isTrue(DslUtils.generateHash(Dsl.create().id(1)) == DslUtils.generateHash(Dsl.create().id(1)), "must equals");
			var id = UUID.fromString("00000000-0000-0000-0000-000000000000");
			put(String.class, Dsl.create().id(id), "test1");
			var hash = getHash(String.class, Dsl.create().id(id));
			var contains = contains(String.class, Dsl.create().id(id));
			var value = Objects.requireNonNull(get(String.class, Dsl.create().id(id)));
			Assert.isTrue(hash.equals("null.String.-569643752"), "must equals");
			Assert.isTrue(contains, "should be contain");
			Assert.isTrue(value.equals("test1"), "value is equal");
			evict(String.class, Dsl.create().id(id));
			contains = contains(String.class, Dsl.create().id(id));
			Assert.isTrue(!contains, "should not contain");
		}
	}

	@Test
	void shouldMonoCacheWorking() {
		var cacheLayer = new CacheTest();
		var id = UUID.randomUUID();
		cacheLayer.putMono(Dsl.create().id(id), "one");
		Assert.isTrue(cacheLayer.containsMono(Dsl.create().id(id)), "hash is contains");

		cacheLayer.getMono(Dsl.create().id(id), Mono.just("two"))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.equals("one"), "must equals"))
				.verifyComplete();

		cacheLayer.getMono(Dsl.create().id(UUID.randomUUID()), Mono.just("two"))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> Assert.isTrue(actual.equals("two"), "must equals"))
				.verifyComplete();
	}

	@Test
	void shouldFluxCacheWorking() {
		var cacheLayer = new CacheTest();
		var id = UUID.randomUUID();
		cacheLayer.putFlux(Dsl.create().id(id), List.of("many"));
		Assert.isTrue(cacheLayer.containsFlux(Dsl.create().id(id)), "hash is contains");

		cacheLayer.getFlux(Dsl.create().id(id), Flux.fromIterable(List.of("many", "mickey"))).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(list -> Assert.isTrue(list.get(0).equals("many"), "must equals"))
				.verifyComplete();

		cacheLayer.getFlux(Dsl.create().id(UUID.randomUUID()), Flux.fromIterable(List.of("many", "mickey"))).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(list -> Assert.isTrue(list.get(1).equals("mickey"), "must equals"))
				.verifyComplete();
	}

	@Test
	void shouldCountByDsl() {
		LegoSet legoSet1 = new LegoSet(null, "SCHAUFELRADBAGGER", 12);
		LegoSet legoSet2 = new LegoSet(null, "FORSCHUNGSSCHIFF", 13);

		repository.saveBatch(List.of(legoSet1, legoSet2))
				.as(StepVerifier::create)
				.expectNextCount(2) //
				.verifyComplete();

		repository.count(Dsl.create())
				.as(StepVerifier::create)
				.consumeNextWith(count -> Assert.isTrue(count == 2, "must equals"))
				.verifyComplete();

		repository.count(Dsl.create().equals("manual", 12))
				.as(StepVerifier::create)
				.consumeNextWith(count -> Assert.isTrue(count == 1, "must equals"))
				.verifyComplete();
	}

	@Test
	void shouldExpressionWork() {
		LegoSet legoSet1 = new LegoSet(null, "SCHAUFELRADBAGGER", 12);
		legoSet1.exp = Objects.requireNonNull(ExpressionParserCache.INSTANCE.parseExpression("a==5"));

		repository.save(legoSet1)
				.as(StepVerifier::create)
				.consumeNextWith(l -> Assert.isTrue(l.id == 1, "must equals"))
				.verifyComplete();

		repository.findById(1)
				.as(StepVerifier::create)
				.consumeNextWith(actual -> {
					Assert.isTrue(actual.getExp().getExpressionString().equals("a==5"), "must equals");
					Assert.isTrue(actual.getName().equals("SCHAUFELRADBAGGER"), "must equals");
					Assert.isTrue(actual.getManual() == 12, "must equals");
				})
				.verifyComplete();
	}

	@Test
	void shouldCacheManage() {
		LegoSet legoSet1 = new LegoSet(null, "SCHAUFELRADBAGGER", 12);

		repository.save(legoSet1)
				.as(StepVerifier::create)
				.expectNextCount(1)
				.verifyComplete();

		repository.findOne(Dsl.create().id(1))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> {
					Assert.isTrue(actual.getName().equals("SCHAUFELRADBAGGER"), "must true");
					Assert.isTrue(Objects.requireNonNull(repository.get(1)).getName().equals("SCHAUFELRADBAGGER"), "must equals");
				})
				.verifyComplete();

		Assert.isTrue(Objects.requireNonNull(repository.get(1)).getName().equals("SCHAUFELRADBAGGER"), "must equals");

		Assert.isTrue(repository.evict(1).get(1) == null, "must equals");

		legoSet1.setId(1);
		Assert.isTrue(Objects.requireNonNull(repository.put(legoSet1).get(1)).getName().equals("SCHAUFELRADBAGGER"), "must equals");

		repository.evictAll();
		Assert.isTrue(repository.get(1) == null, "must equals");
	}

	@Test
	void shouldCacheMonoToFlux() {
		LegoSet legoSet1 = new LegoSet(null, "SCHAUFELRADBAGGER", 12);

		repository.evictAll().save(legoSet1)
				.as(StepVerifier::create)
				.expectNextCount(1)
				.verifyComplete();

		repository.findAll(Dsl.create().id(1))
				.as(StepVerifier::create)
				.consumeNextWith(actual -> {
					Assert.isTrue(actual.getName().equals("SCHAUFELRADBAGGER"), "must true");
					Assert.isTrue(Objects.requireNonNull(repository.get(1)).getName().equals("SCHAUFELRADBAGGER"), "must equals");
				})
				.verifyComplete();
	}

	@Test
	void shouldCacheSaveAndFlux() {
		LegoSet legoSet1 = new LegoSet(null, "SCHAUFELRADBAGGER", 12);
		repository.deleteAll().block();

		repository.save(legoSet1)
				.as(StepVerifier::create)
				.expectNextCount(1)
				.verifyComplete();

		repository.evictAll().findAll(Dsl.create()).collectList()
				.as(StepVerifier::create)
				.consumeNextWith(actual -> {
					Assert.isTrue(actual.get(0).getName().equals("SCHAUFELRADBAGGER"), "must true");
					Assert.isTrue(Objects.requireNonNull(repository.get(1)).getName().equals("SCHAUFELRADBAGGER"), "must equals");
				})
				.verifyComplete();
	}

	@AfterAll
	void shutdown() {
		Hazelcast.shutdownAll();
	}
}
